title: 绿森林软件基地 
author: 绿森林 
developer_group: 614163659 
outsource_group: 468246369
githuburl: https://github.com/zhousning
resumeurl: http://www.qlrc.com/company/cv/cvview?id=26813126
description: 个人博客 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
motto: 分享改变世界
twitter_username: jekyllrb
github_username:  zhousning

# Build settings
markdown: kramdown
permalink: none 

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
